# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  page-elements:
    environment:
      - NIM_TRITON_MAX_BATCH_SIZE=1

  graphic-elements:
    environment:
      - NIM_TRITON_MAX_BATCH_SIZE=1

  table-structure:
    environment:
      - NIM_TRITON_MAX_BATCH_SIZE=1

  ocr:
    environment:
      - NIM_TRITON_MAX_BATCH_SIZE=1

  reranker:
    environment:
      - NIM_TRITON_MAX_BATCH_SIZE=1
