{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.embedqa.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: llama-3.2-nv-embedqa-1b-v2
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ .Values.nimOperator.embedqa.image.repository }}:{{ .Values.nimOperator.embedqa.image.tag }}"
      pullSecret: "{{ index .Values.nimOperator.embedqa.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.embedqa.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.embedqa.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.embedqa.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.embedqa.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.embedqa.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: llama-32-nv-embedqa-1b-v2
spec:
  image:
    repository: {{ .Values.nimOperator.embedqa.image.repository }}
    tag: {{ .Values.nimOperator.embedqa.image.tag }}
    pullPolicy: {{ .Values.nimOperator.embedqa.image.pullPolicy }}
    pullSecrets:
{{ toYaml .Values.nimOperator.embedqa.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.embedqa.authSecret }}
  storage:
    nimCache:
      name: llama-3.2-nv-embedqa-1b-v2
  replicas: {{ .Values.nimOperator.embedqa.replicas }}
  nodeSelector:
{{ toYaml .Values.nimOperator.embedqa.nodeSelector | nindent 4 }}
{{- if .Values.nimOperator.draResources.enabled }}
  draResources:
{{ toYaml .Values.nimOperator.llama_3_2_nv_rerankqa_1b_v2.draResources | nindent 4 }}
{{- end }}
{{- if not .Values.nimOperator.draResources.enabled }}
  resources:
{{ toYaml .Values.nimOperator.llama_3_2_nv_rerankqa_1b_v2.resources | nindent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.nimOperator.embedqa.tolerations | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.embedqa.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.embedqa.env | nindent 4 }}
{{- end }}