{{- if .Values.nimOperator.embedqa.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-32-nv-embedqa-1b-v2
spec:
  replicas: {{ .Values.nimOperator.embedqa.replicas }}
  selector:
    matchLabels:
      app: llama-32-nv-embedqa-1b-v2
  template:
    metadata:
      labels:
        app: llama-32-nv-embedqa-1b-v2
    spec:
      {{- if .Values.nimOperator.embedqa.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.nimOperator.embedqa.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.nimOperator.embedqa.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nimOperator.embedqa.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.nimOperator.embedqa.tolerations }}
      tolerations:
{{ toYaml .Values.nimOperator.embedqa.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: llama-32-nv-embedqa-1b-v2
          image: "{{ .Values.nimOperator.embedqa.image.repository }}:{{ .Values.nimOperator.embedqa.image.tag }}"
          imagePullPolicy: {{ .Values.nimOperator.embedqa.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 8000 .Values.nimOperator.embedqa.expose.service.port }}
            - name: grpc
              containerPort: {{ default 8001 .Values.nimOperator.embedqa.expose.service.grpcPort }}
          {{- if .Values.nimOperator.embedqa.env }}
          env:
{{ toYaml .Values.nimOperator.embedqa.env | indent 12 }}
          {{- end }}
          {{- if .Values.nimOperator.embedqa.resources }}
          resources:
{{ toYaml .Values.nimOperator.embedqa.resources | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: llama-32-nv-embedqa-1b-v2
spec:
  type: {{ default "ClusterIP" .Values.nimOperator.embedqa.expose.service.type }}
  selector:
    app: llama-32-nv-embedqa-1b-v2
  ports:
    - name: http
      port: {{ default 8000 .Values.nimOperator.embedqa.expose.service.port }}
      targetPort: {{ default 8000 .Values.nimOperator.embedqa.expose.service.port }}
    - name: grpc
      port: {{ default 8001 .Values.nimOperator.embedqa.expose.service.grpcPort }}
      targetPort: {{ default 8001 .Values.nimOperator.embedqa.expose.service.grpcPort }}
{{- end }}
