{{- if .Values.nimOperator.page_elements.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemoretriever-page-elements-v3
spec:
  replicas: {{ .Values.nimOperator.page_elements.replicas }}
  selector:
    matchLabels:
      app: nemoretriever-page-elements-v3
  template:
    metadata:
      labels:
        app: nemoretriever-page-elements-v3
    spec:
      {{- if .Values.nimOperator.page_elements.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.nimOperator.page_elements.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.nimOperator.page_elements.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nimOperator.page_elements.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.nimOperator.page_elements.tolerations }}
      tolerations:
{{ toYaml .Values.nimOperator.page_elements.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: nemoretriever-page-elements-v3
          image: "{{ .Values.nimOperator.page_elements.image.repository }}:{{ .Values.nimOperator.page_elements.image.tag }}"
          imagePullPolicy: {{ .Values.nimOperator.page_elements.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 8000 .Values.nimOperator.page_elements.expose.service.port }}
            - name: grpc
              containerPort: {{ default 8001 .Values.nimOperator.page_elements.expose.service.grpcPort }}
          {{- if .Values.nimOperator.page_elements.env }}
          env:
{{ toYaml .Values.nimOperator.page_elements.env | indent 12 }}
          {{- end }}
          {{- if .Values.nimOperator.page_elements.resources }}
          resources:
{{ toYaml .Values.nimOperator.page_elements.resources | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nemoretriever-page-elements-v3
spec:
  type: {{ default "ClusterIP" .Values.nimOperator.page_elements.expose.service.type }}
  selector:
    app: nemoretriever-page-elements-v3
  ports:
    - name: http
      port: {{ default 8000 .Values.nimOperator.page_elements.expose.service.port }}
      targetPort: {{ default 8000 .Values.nimOperator.page_elements.expose.service.port }}
    - name: grpc
      port: {{ default 8001 .Values.nimOperator.page_elements.expose.service.grpcPort }}
      targetPort: {{ default 8001 .Values.nimOperator.page_elements.expose.service.grpcPort }}
{{- end }}
