{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.nemotron_parse.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nemotron-parse
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ include "nv-ingest.release.nimRef" (dict "root" . "key" "nemotron_parse") }}"
      pullSecret: "{{ index .Values.nimOperator.nemotron_parse.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.nemotron_parse.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.nemotron_parse.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.nemotron_parse.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.nemotron_parse.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.nemotron_parse.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemotron-parse
spec:
  image:
    repository: {{ include "nv-ingest.release.nimRepository" (dict "root" . "key" "nemotron_parse") }}
    tag: {{ include "nv-ingest.release.nimTag" (dict "root" . "key" "nemotron_parse") }}
    pullPolicy: IfNotPresent
    pullSecrets:
{{ toYaml .Values.nimOperator.nemotron_parse.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.nemotron_parse.authSecret }}
  storage:
    nimCache:
      name: nemotron-parse
  replicas: {{ .Values.nimOperator.nemotron_parse.replicas }}
  resources:
{{ toYaml .Values.nimOperator.nemotron_parse.resources | nindent 4 }}
  tolerations:
{{ toYaml .Values.nimOperator.nemotron_parse.tolerations | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.nemotron_parse.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.nemotron_parse.env | nindent 4 }}
{{- end }}
