{{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemotron-nano-12b-v2-vl
spec:
  replicas: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.replicas }}
  selector:
    matchLabels:
      app: nemotron-nano-12b-v2-vl
  template:
    metadata:
      labels:
        app: nemotron-nano-12b-v2-vl
    spec:
      {{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.nimOperator.nemotron_nano_12b_v2_vl.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.tolerations }}
      tolerations:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: nemotron-nano-12b-v2-vl
          image: "{{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.repository }}:{{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ default 8000 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.port }}
            - name: grpc
              containerPort: {{ default 8001 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.grpcPort }}
          {{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.env }}
          env:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.env | indent 12 }}
          {{- end }}
          {{- if .Values.nimOperator.nemotron_nano_12b_v2_vl.resources }}
          resources:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.resources | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nemotron-nano-12b-v2-vl
spec:
  type: {{ default "ClusterIP" .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.type }}
  selector:
    app: nemotron-nano-12b-v2-vl
  ports:
    - name: http
      port: {{ default 8000 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.port }}
      targetPort: {{ default 8000 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.port }}
    - name: grpc
      port: {{ default 8001 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.grpcPort }}
      targetPort: {{ default 8001 .Values.nimOperator.nemotron_nano_12b_v2_vl.expose.service.grpcPort }}
{{- end }}
