{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.table_structure.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nemoretriever-table-structure-v1
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ .Values.nimOperator.table_structure.image.repository }}:{{ .Values.nimOperator.table_structure.image.tag }}"
      pullSecret: "{{ index .Values.nimOperator.table_structure.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.table_structure.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.table_structure.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.table_structure.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.table_structure.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.table_structure.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemoretriever-table-structure-v1
spec:
  image:
    repository: {{ .Values.nimOperator.table_structure.image.repository }}
    tag: {{ .Values.nimOperator.table_structure.image.tag }}
    pullPolicy: {{ .Values.nimOperator.table_structure.image.pullPolicy }}
    pullSecrets:
{{ toYaml .Values.nimOperator.table_structure.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.table_structure.authSecret }}
  storage:
    nimCache:
      name: nemoretriever-table-structure-v1
  replicas: {{ .Values.nimOperator.table_structure.replicas }}
  nodeSelector:
{{ toYaml .Values.nimOperator.table_structure.nodeSelector | nindent 4 }}
  resources:
{{ toYaml .Values.nimOperator.table_structure.resources | nindent 4 }}
  tolerations:
{{ toYaml .Values.nimOperator.table_structure.tolerations | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.table_structure.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.table_structure.env | nindent 4 }}
{{- end }}
