{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.graphic_elements.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nemoretriever-graphic-elements-v1
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ include "nv-ingest.release.nimRef" (dict "root" . "key" "graphic_elements") }}"
      pullSecret: "{{ index .Values.nimOperator.graphic_elements.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.graphic_elements.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.graphic_elements.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.graphic_elements.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.graphic_elements.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.graphic_elements.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemoretriever-graphic-elements-v1
spec:
  image:
    repository: {{ include "nv-ingest.release.nimRepository" (dict "root" . "key" "graphic_elements") }}
    tag: {{ include "nv-ingest.release.nimTag" (dict "root" . "key" "graphic_elements") }}
    pullPolicy: {{ .Values.nimOperator.graphic_elements.image.pullPolicy }}
    pullSecrets:
{{ toYaml .Values.nimOperator.graphic_elements.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.graphic_elements.authSecret }}
  storage:
    nimCache:
      name: nemoretriever-graphic-elements-v1
  replicas: {{ .Values.nimOperator.graphic_elements.replicas }}
  nodeSelector:
{{ toYaml .Values.nimOperator.graphic_elements.nodeSelector | nindent 4 }}
  resources:
{{ toYaml .Values.nimOperator.graphic_elements.resources | nindent 4 }}
  tolerations:
{{ toYaml .Values.nimOperator.graphic_elements.tolerations | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.graphic_elements.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.graphic_elements.env | nindent 4 }}
{{- end }}
