{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.nemotron_nano_12b_v2_vl.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: nemotron-nano-12b-v2-vl
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.repository }}:{{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.tag }}"
      pullSecret: "{{ index .Values.nimOperator.nemotron_nano_12b_v2_vl.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: nemotron-nano-12b-v2-vl
spec:
  image:
    repository: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.repository }}
    tag: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.image.tag }}
    pullPolicy: IfNotPresent
    pullSecrets:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.authSecret }}
  storage:
    nimCache:
      name: nemotron-nano-12b-v2-vl
  replicas: {{ .Values.nimOperator.nemotron_nano_12b_v2_vl.replicas }}
{{- if .Values.nimOperator.draResources.enabled }}
  draResources:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.draResources | nindent 4 }}
{{- end }}
{{- if not .Values.nimOperator.draResources.enabled }}
  resources:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.resources | nindent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.tolerations | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.nemotron_nano_12b_v2_vl.env | nindent 4 }}
{{- end }}
