{{- if .Values.nimOperator.paddleocr.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paddleocr
spec:
  replicas: {{ .Values.nimOperator.paddleocr.replicas }}
  selector:
    matchLabels:
      app: paddleocr
  template:
    metadata:
      labels:
        app: paddleocr
    spec:
      {{- if .Values.nimOperator.paddleocr.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.nimOperator.paddleocr.image.pullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.nimOperator.paddleocr.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nimOperator.paddleocr.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.nimOperator.paddleocr.tolerations }}
      tolerations:
{{ toYaml .Values.nimOperator.paddleocr.tolerations | indent 8 }}
      {{- end }}
      containers:
        - name: paddleocr
          image: "{{ .Values.nimOperator.paddleocr.image.repository }}:{{ .Values.nimOperator.paddleocr.image.tag }}"
          imagePullPolicy: {{ .Values.nimOperator.paddleocr.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nimOperator.paddleocr.expose.service.port }}
            - name: grpc
              containerPort: {{ .Values.nimOperator.paddleocr.expose.service.grpcPort }}
          {{- if .Values.nimOperator.paddleocr.env }}
          env:
{{ toYaml .Values.nimOperator.paddleocr.env | indent 12 }}
          {{- end }}
          {{- if .Values.nimOperator.paddleocr.resources }}
          resources:
{{ toYaml .Values.nimOperator.paddleocr.resources | indent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: paddleocr
spec:
  type: {{ default "ClusterIP" .Values.nimOperator.paddleocr.expose.service.type }}
  selector:
    app: paddleocr
  ports:
    - name: http
      port: {{ .Values.nimOperator.paddleocr.expose.service.port }}
      targetPort: {{ .Values.nimOperator.paddleocr.expose.service.port }}
    - name: grpc
      port: {{ .Values.nimOperator.paddleocr.expose.service.grpcPort }}
      targetPort: {{ .Values.nimOperator.paddleocr.expose.service.grpcPort }}
{{- end }}
