{{ if and (.Capabilities.APIVersions.Has "apps.nvidia.com/v1alpha1") (eq .Values.nimOperator.paddleocr.enabled true) -}}
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: paddleocr
  annotations:
    helm.sh/resource-policy: keep
spec:
  source:
    ngc:
      modelPuller: "{{ .Values.nimOperator.paddleocr.image.repository }}:{{ .Values.nimOperator.paddleocr.image.tag }}"
      pullSecret: "{{ index .Values.nimOperator.paddleocr.image.pullSecrets 0 }}"
      authSecret: {{ .Values.nimOperator.paddleocr.authSecret }}
  storage:
    pvc:
      create: {{ .Values.nimOperator.paddleocr.storage.pvc.create }}
      storageClass: {{ .Values.nimOperator.paddleocr.storage.pvc.storageClass }}
      size: {{ .Values.nimOperator.paddleocr.storage.pvc.size }}
      volumeAccessMode: {{ .Values.nimOperator.paddleocr.storage.pvc.volumeAccessMode }}
---
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: paddleocr
spec:
  image:
    repository: {{ .Values.nimOperator.paddleocr.image.repository }}
    tag: {{ .Values.nimOperator.paddleocr.image.tag }}
    pullPolicy: {{ .Values.nimOperator.paddleocr.image.pullPolicy }}
    pullSecrets:
{{ toYaml .Values.nimOperator.paddleocr.image.pullSecrets | nindent 6 }}
  authSecret: {{ .Values.nimOperator.paddleocr.authSecret }}
  storage:
    nimCache:
      name: paddleocr
  replicas: {{ .Values.nimOperator.paddleocr.replicas }}
  resources:
{{ toYaml .Values.nimOperator.paddleocr.resources | nindent 4 }}
  expose:
{{ toYaml .Values.nimOperator.paddleocr.expose | nindent 4 }}
  env:
{{ toYaml .Values.nimOperator.paddleocr.env | nindent 4 }}
{{- end }}
