name: nv_ingest_api
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - diskcache>=5.6.3
  - pydantic>2.0.0
  - pydantic-settings>2.0.0
  - pytest>=8.0.2
  - pytest-mock>=3.14.0
  - pytest-cov>=6.0.0
  - python>=3.12
  - python-build>=1.2.2
  - setuptools>=58.2.0
  - s3fs>=2024.10.0
  - pip
