name: nv_ingest_api
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - pydantic>2.0.0
  - pydantic-settings>2.0.0
  - pytest>=8.0.2
  - pytest-mock>=3.14.0
  - pytest-cov>=6.0.0
  - python>=3.12
  - python-build>=1.2.2
  - setuptools>=75.8.2
  - pip
