name: nv_ingest_client
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - click>=8.1.7
  - diskcache>=5.6.3
  - fsspec>=2024.10.0
  - s3fs>=2024.10.0
  - httpx>=0.28.1
  - pydantic>=2.10.3
<<<<<<< Updated upstream
  - pypdfium2==4.30.0
=======
  - pypdfium2>=4.30.0,<5.0.0
>>>>>>> Stashed changes
  - pytest>=8.0.2
  - pytest-mock>=3.14.0
  - pytest-cov>=6.0.0
  - python>=3.12
  - python-build>=1.2.2
  - python-docx>=1.1.2
  - python-pptx>=1.0.2
  - requests>=2.28.2
  - setuptools>=58.2.0
  - tqdm>=4.67.1
  - pip
