name: nv_ingest_runtime
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - azure-core>=1.32.0
  - click>=8.1.7
  - diskcache>=5.6.3
  - fastapi>=0.115.6
  - fastparquet>=2024.11.0
  - fsspec>=2024.10.0
  - gunicorn
  - h11>=0.16.0 # Must pin at or above 0.16.0 for CVE mitigation
  - httpx>=0.28.1
  - isodate>=0.7.2
  - langdetect>=1.0.9
  - minio>=7.2.12
  - openai>=1.82.0
  - opentelemetry-api>=1.27.0
  - opentelemetry-exporter-otlp>=1.27.0
  - opentelemetry-sdk>=1.27.0
  - protobuf=5.29.3
  - pydantic>2.0.0
  - pydantic-settings>2.0.0
  - pypdfium2>=4.30.0
  - pytest>=8.0.2
  - pytest-mock>=3.14.0
  - pytest-cov>=6.0.0
  - python>=3.12.11,<3.13
  - python-build>=1.2.2
  - python-docx>=1.1.2
  - python-dotenv>=1.0.1
  - python-pptx>=1.0.2
  - ray-all>=2.49.0
  - redis-py>=5.2.1
  - requests>=2.28.2
  - scikit-learn>=1.6.0
  - scipy>=1.15.1
  - setuptools>=58.2.0
  - tabulate>=0.9.0
  - transformers>=4.47.0
  - tqdm>=4.67.1
  - uvicorn
  - pip
  - pip:
      - llama-index-embeddings-nvidia
      - milvus-lite==2.4.12
      - opencv-python # For some reason conda cant solve our req set with py-opencv so we need to use pip
      - prometheus-client
      - pymilvus>=2.5.0
      - pymilvus[bulk_writer, model]
      - tritonclient
      - nvidia-riva-client==2.20.0
      - unstructured-client
      - markitdown
      - s3fs>=2025.9.0 # AWS S3 fsspec support
      - boto3>=1.39.11 # AWS S3 fsspec support
