name: nv_ingest_runtime
channels:
  - nvidia/label/dev
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adagio=0.2.4=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_0
  - alembic=1.14.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - antlr-python-runtime=4.11.1=pyhd8ed1ab_0
  - antlr4-python3-runtime=4.11.1=pyh1a96a4e_0
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asn1crypto=1.5.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=he1a10d6_2
  - aws-c-cal=0.7.4=hae4d56a_2
  - aws-c-common=0.9.29=hb9d3cd8_0
  - aws-c-compression=0.2.19=h2bff981_2
  - aws-c-event-stream=0.4.3=h19b0707_4
  - aws-c-http=0.8.10=h14a7884_2
  - aws-c-io=0.14.19=hc9e6898_1
  - aws-c-mqtt=0.10.7=hb8d5873_2
  - aws-c-s3=0.6.7=h666547d_0
  - aws-c-sdkutils=0.1.19=h2bff981_4
  - aws-checksums=0.1.20=h2bff981_1
  - aws-crt-cpp=0.28.3=hbe26082_8
  - aws-sdk-cpp=1.11.407=h25d6d5c_1
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - azure-storage-files-datalake-cpp=12.11.0=h325d260_1
  - babel=2.16.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - blinker=1.9.0=pyhff2d567_0
  - bokeh=3.6.1=pyhd8ed1ab_0
  - boost-cpp=1.84.0=h3c6214e_6
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.18.0=hebfffa5_3
  - cattrs=24.1.2=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.3.1=py310h3788b33_0
  - cryptography=43.0.3=py310h6c63255_0
  - cuda-cccl_linux-64=12.5.39=0
  - cuda-crt-dev_linux-64=12.5.82=0
  - cuda-crt-tools=12.5.82=0
  - cuda-cudart=12.5.82=0
  - cuda-cudart-dev=12.5.82=0
  - cuda-cudart-dev_linux-64=12.5.82=0
  - cuda-cudart-static=12.5.82=0
  - cuda-cudart-static_linux-64=12.5.82=0
  - cuda-cudart_linux-64=12.5.82=0
  - cuda-nvcc-dev_linux-64=12.5.82=0
  - cuda-nvcc-impl=12.5.82=0
  - cuda-nvcc-tools=12.5.82=0
  - cuda-nvrtc=12.5.82=0
  - cuda-nvtx=12.5.82=0
  - cuda-nvvm-dev_linux-64=12.5.82=0
  - cuda-nvvm-impl=12.5.82=0
  - cuda-nvvm-tools=12.5.82=0
  - cuda-python=12.6.0=py310h7ffcb74_0
  - cuda-version=12.5=3
  - cudf=24.10.01=cuda12_py310_241009_g7b0adfa253_0
  - cupy=13.3.0=py310h1b77274_2
  - cupy-core=13.3.0=py310h8de46e0_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - cytoolz=1.0.0=py310ha75aee5_1
  - dask=2024.9.0=pyhd8ed1ab_0
  - dask-core=2024.9.0=pyhd8ed1ab_0
  - dask-expr=1.1.14=pyhd8ed1ab_0
  - databricks-sdk=0.37.0=pyhd8ed1ab_0
  - datacompy=0.10.5=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - deprecated=1.2.15=pyhff2d567_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distributed=2024.9.0=pyhd8ed1ab_0
  - dlpack=0.8=h59595ed_3
  - docker-py=5.0.3=pyhd8ed1ab_4
  - docker-pycreds=0.4.0=py_0
  - docutils=0.21.2=pyhd8ed1ab_0
  - elastic-transport=8.15.1=pyhd8ed1ab_0
  - elasticsearch=8.9.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - fastrlock=0.8.2=py310hc6cd4ac_2
  - feedparser=6.0.11=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - flask=3.1.0=pyhff2d567_0
  - fmt=11.0.2=h434a139_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.0=py310h89163eb_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.5.0=py310ha75aee5_0
  - fs=2.4.16=pyhd8ed1ab_0
  - fsspec=2024.10.0=pyhff2d567_0
  - fugue=0.8.7=pyhd8ed1ab_0
  - fugue-sql-antlr=0.2.2=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gflags=2.2.2=h5888daf_1005
  - ghostscript=10.04.0=h5888daf_0
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.7.1=hbabe93e_0
  - google-auth=2.36.0=pyhff2d567_0
  - graphene=3.4.3=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - graphql-core=3.2.5=pyhd8ed1ab_0
  - graphql-relay=3.2.0=pyhd8ed1ab_0
  - graphviz=12.0.0=hba01fac_0
  - greenlet=3.1.1=py310hf71b8c6_0
  - gtk2=2.24.33=h6470451_5
  - gts=0.7.6=h977cf35_4
  - gunicorn=22.0.0=py310hff52083_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - imagemagick=7.1.1_41=imagemagick_hcfc5581_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarrow=17.0.0=had3b6fe_16_cpu
  - libarrow-acero=17.0.0=h5888daf_16_cpu
  - libarrow-dataset=17.0.0=h5888daf_16_cpu
  - libarrow-substrait=17.0.0=hf54134d_16_cpu
  - libavif16=1.1.1=h1909e37_2
  - libblas=3.9.0=25_linux64_openblas
  - libboost=1.84.0=hb8260a3_6
  - libboost-devel=1.84.0=h1a2810e_6
  - libboost-headers=1.84.0=ha770c72_6
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=25_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.5.3.2=0
  - libcudf=24.10.01=cuda12_241009_g7b0adfa253_0
  - libcufft=11.2.3.61=0
  - libcufile=1.10.1.7=0
  - libcufile-dev=1.10.1.7=0
  - libcurand=10.3.6.82=0
  - libcurl=8.10.1=hbbe4b11_0
  - libcusolver=11.6.3.83=0
  - libcusparse=12.5.1.3=0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgd=2.3.3=hd3e95f3_10
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.29.0=h435de7b_0
  - libgoogle-cloud-storage=2.29.0=h0121fbd_0
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.62.2=h15f2491_0
  - libheif=1.18.2=gpl_hffcb242_100
  - libhwloc=2.9.2=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - libkvikio=24.10.00=cuda12_241009_g85a88a2_0
  - liblapack=3.9.0=25_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libmrc=24.10.00a=cuda_12.5_h1b95675_10
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libnvjitlink=12.5.82=0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libparquet=17.0.0=h39682fd_16_cpu
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - librdkafka=1.9.2=ha5a0de0_2
  - libre2-11=2023.09.01=h5a48ba9_2
  - librmm=24.10.00=cuda12_241009_g3223f841_0
  - librsvg=2.58.4=hc0ffecb_0
  - libsqlite=3.47.0=hadc24fc_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.7=h2774228_1
  - libthrift=0.20.0=h0e7cc3e_1
  - libtiff=4.7.0=he137b08_1
  - libudev1=256.7=hb9d3cd8_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hb346dea_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py310h1a6248f_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=5.3.0=py310h6ee67d5_2
  - lz4=4.3.3=py310hb259640_1
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.6=pyhff2d567_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h89163eb_0
  - matplotlib-base=3.9.2=py310h68603db_2
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mlflow=2.17.2=hff52083_0
  - mlflow-skinny=2.17.2=py310hff52083_0
  - mlflow-ui=2.17.2=py310hff52083_0
  - morpheus-core=24.10.00a=cuda_12.5_py3.10_g0a172049_114
  - morpheus-llm=24.10.00a=cuda_12.5_py3.10_g0a172049_114
  - mrc=24.10.00a=cuda_12.5_py310_h5ae46af_10
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.1.0=py310h89163eb_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=he02047a_1
  - networkx=2.8.8=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=he02047a_1
  - numba=0.60.0=py310h5dc88bb_0
  - numpy=1.26.0=py310hb13e2d6_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - nvcomp=4.0.1=hbc370b7_0
  - nvtx=0.2.10=py310ha75aee5_2
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.0=hb9d3cd8_0
  - orc=2.0.2=h669347b_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - pango=1.54.0=h4c5309f_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.2=h59595ed_0
  - pkg-config=0.29.2=h4bc722e_1009
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.1=pyhd8ed1ab_0
  - propcache=0.2.0=py310ha75aee5_2
  - protobuf=4.25.3=py310h0e2eeba_1
  - psutil=6.1.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=17.0.0=py310hb7f781d_2
  - pyarrow-core=17.0.0=py310hac404ae_2_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic-core=2.23.4=py310h505e2c1_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pylibcudf=24.10.01=cuda12_py310_241009_g7b0adfa253_0
  - pynvjitlink=0.4.0=py310hcc76453_0
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.15=h4a871b0_2_cpython
  - python-confluent-kafka=1.9.2=py310h5764c6d_2
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-graphviz=0.20.3=pyhe28f650_1
  - python-rapidjson=1.20=py310hea249c9_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.2=py310ha75aee5_1
  - qhull=2020.2=h434a139_5
  - qpd=0.4.4=pyhd8ed1ab_1
  - querystring_parser=1.2.4=pyhd8ed1ab_1
  - rapids-dask-dependency=24.10.00=py_0
  - rav1e=0.6.6=he8a937b_2
  - rdma-core=54.0=h5888daf_1
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rmm=24.10.00=cuda12_py310_241009_g3223f841_0
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.5.5=h3931f03_0
  - scikit-learn=1.3.2=py310h1fdf081_2
  - scipy=1.14.1=py310hfcf56fc_1
  - sgmllib3k=1.0.0=pyh9f0ad1d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.2.1=ha2e4443_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.14.1=hed91bc2_1
  - sphinx=8.1.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - sqlalchemy=1.4.54=py310ha75aee5_0
  - sqlglot=25.30.0=pyhff2d567_1
  - sqlparse=0.5.2=pyhff2d567_0
  - svt-av1=2.3.0=h5888daf_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tini=0.19.0=h166bdaf_1
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.1.0=pyhff2d567_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py310ha75aee5_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - triad=0.9.8=pyhd8ed1ab_0
  - tritonclient=2.34.0=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - ucx=1.15.0=hda83522_8
  - ujson=5.10.0=py310hf71b8c6_1
  - unicodedata2=15.1.0=py310ha75aee5_1
  - url-normalize=1.4.3=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - watchdog=3.0.0=py310hff52083_1
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - websockets=14.1=py310ha75aee5_0
  - werkzeug=3.1.3=pyhff2d567_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py310ha75aee5_1
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.17.2=py310ha75aee5_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.1.1
      - aiobotocore==2.15.2
      - aiohttp==3.10.11
      - aioitertools==0.12.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asgiref==3.8.1
      - autoflake==2.3.1
      - azure-ai-formrecognizer==3.3.3
      - azure-common==1.1.28
      - azure-core==1.32.0
      - backoff==2.2.1
      - black==23.11.0
      - boilerpy3==1.0.7
      - botocore==1.35.36
      - cfgv==3.4.0
      - coverage==7.6.8
      - cramjam==2.9.0
      - dataclasses==0.6
      - dataclasses-json==0.6.7
      - deepdiff==8.0.1
      - distlib==0.3.9
      - distro==1.9.0
      - docopt==0.6.2
      - environs==9.5.0
      - events==0.5
      - faiss-gpu==1.7.2
      - farm-haystack==1.26.4
      - fastapi==0.109.1
      - fastparquet==2024.2.0
      - filelock==3.16.1
      - flake8==7.0.0
      - google-search-results==2.4.0
      - googleapis-common-protos==1.66.0
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.26.3
      - identify==2.6.3
      - importlib-metadata==8.4.0
      - inflect==7.4.0
      - iniconfig==2.0.0
      - isodate==0.7.2
      - isort==5.13.2
      - jiter==0.8.0
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - langchain==0.1.16
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-nvidia-ai-endpoints==0.0.11
      - langchain-text-splitters==0.0.2
      - langdetect==1.0.9
      - langsmith==0.1.147
      - lazy-imports==0.3.1
      - marshmallow==3.23.1
      - mccabe==0.7.0
      - milvus==2.3.5
      - minio==7.2.12
      - monotonic==1.6
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msrest==0.7.1
      - mypy-extensions==1.0.0
      - nemollm==0.3.5
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - nodeenv==1.9.1
      - num2words==0.5.13
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - olefile==0.47
      - onnx==1.17.0
      - openai==1.40.6
      - opencv-python==4.10.0.84
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-exporter-otlp-proto-http==1.27.0
      - opentelemetry-instrumentation==0.48b0
      - opentelemetry-instrumentation-asgi==0.48b0
      - opentelemetry-instrumentation-fastapi==0.48b0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opentelemetry-util-http==0.48b0
      - orderly-set==5.2.2
      - orjson==3.10.12
      - packaging==23.2
      - pandas==1.5.3
      - pathspec==0.12.1
      - pdf2image==1.17.0
      - pillow==10.4.0
      - posthog==3.7.4
      - pre-commit==3.5.0
      - prompthub-py==4.0.0
      - pycodestyle==2.11.1
      - pycryptodome==3.21.0
      - pydantic==1.10.14
      - pyflakes==3.2.0
      - pyinstrument==5.0.0
      - pymilvus==2.3.6
      - pypdf==5.1.0
      - pypdfium2==4.30.0
      - pytesseract==0.3.13
      - pytest==7.4.3
      - pytest-cov==4.1.0
      - pytest-mock==3.14.0
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-frontmatter==1.1.0
      - python-magic==0.4.27
      - python-multipart==0.0.19
      - python-pptx==0.6.23
      - quantulum3==0.9.2
      - rank-bm25==0.2.2
      - redis==5.0.8
      - referencing==0.35.1
      - regex==2024.11.6
      - requests-cache==0.9.8
      - requests-futures==1.0.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rpds-py==0.22.1
      - s3fs==2024.10.0
      - safetensors==0.4.5
      - sentence-transformers==3.0.0
      - sentencepiece==0.2.0
      - setuptools==70.0.0
      - sniffio==1.3.1
      - sseclient-py==1.8.0
      - starlette==0.35.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tika==2.6.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - torch==2.3.0
      - torchvision==0.18.0
      - transformers==4.46.3
      - triton==2.3.0
      - typeguard==4.4.1
      - typing-inspect==0.9.0
      - unstructured-client==0.23.3
      - uvicorn==0.24.0.post1
      - virtualenv==20.28.0
      - wand==0.6.13
      - xlsxwriter==3.2.0
      - yapf==0.40.2
