name: Nv-Ingest Conda Package Publish

# Trigger for pull requests and pushing to main
on:
  schedule:
    # Runs every day at 11:30PM (UTC)
    - cron: "30 23 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      CONDA_CHANNEL:
        description: 'The RapidsAI Conda channel the package should be pushed to'
        required: true
        type: choice
        options:
          - dev
          - main
      VERSION:
        description: 'Version string for the release (e.g., 1.0.0)'
        required: true

jobs:
  build:
    runs-on: linux-large-disk
    container:
      image: rapidsai/ci-conda:cuda12.5.1-ubuntu22.04-py3.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Determine CONDA_CHANNEL
        run: |
          echo "Github event_name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Setting Conda channel to ${{ github.event.inputs.CONDA_CHANNEL }}"
            echo "CONDA_CHANNEL=${{ github.event.inputs.CONDA_CHANNEL }}" >> $GITHUB_ENV
          else
            echo "CONDA_CHANNEL=dev" >> $GITHUB_ENV
          fi

      # Build the Conda packages
      - name: Build Conda Packages
        run: |
          echo "Github event_name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Building conda package for ${{ github.event.inputs.VERSION }}"
            RELEASE_VERSION="${{ github.event.inputs.VERSION }}" ./conda/build_conda_packages.sh
          else
            ./conda/build_conda_packages.sh
          fi

      # Publish nv-ingest conda packages
      - name: Publish conda package
        run: anaconda -t "${{ secrets.NVIDIA_CONDA_TOKEN }}" upload --force --label $CONDA_CHANNEL ./conda/output_conda_channel/linux-64/*.conda
