name: Library Mode Integration Test

on:
  #workflow_run:
  #  workflows:
  #    - Build Conda Packages
  #  types:
  #    - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by ${{ github.event.workflow_run.id }}"
